services:
  db:
    image: postgres:16-alpine
    container_name: postgresSQL
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1"]
      interval: 10s
      timeout: 10s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app:cached       # 소스 코드만 공유
      - /app/.venv          # 컨테이너 내부 전용 가상환경
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    restart: unless-stopped

volumes:
  pg_data:

#    docker-compose --env-file .env.prod up -d --build  뭔 짓을해도 자꾸 .env 못 읽어올 때 강제로 읽게해버리는 명령어
#            docker-compose down --remove-orphans
#
#            docker system prune -f
#            docker image prune -f
#            docker container prune -f

#  web 컨테이너 안에서 gunicorn + celery worker/beat를 subprocess로 통합 실행 : t2.micro 환경 고려한 것
# restart 아래로 추가하면 됨 or run.sh에서 관리하기.
#    command: >
#      sh -c "
#        gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers=3 &
#        celery -A config worker -l info --concurrency=2 &
#        celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
#      "