[pytest]
DJANGO_SETTINGS_MODULE = config.settings.dev
python_files = tests.py test_*.py *_tests.py



# dev 환경
# $env:DJANGO_SETTINGS_MODULE="config.settings.dev"
# uv run pytest

# prod 환경
# $env:DJANGO_SETTINGS_MODULE="config.settings.prod"
# uv run pytest

# pytest 사용 후 coverage를 html 파일로 작성해주는 명령어
# uv run pytest --cov=apps --cov=tests --cov-report=html