# Generated by Django 5.2.6 on 2025-09-30 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularQuery",
            fields=[
                (
                    "query",
                    models.TextField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="정규화된 검색어",
                    ),
                ),
                ("cnt", models.BigIntegerField(verbose_name="검색 횟수")),
                ("last_seen", models.DateTimeField(verbose_name="마지막 검색 시각")),
            ],
            options={
                "verbose_name": "인기 검색어",
                "verbose_name_plural": "인기 검색어 목록",
                "db_table": "popular_queries_mv",
                "ordering": ["-cnt"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RecommendedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField(verbose_name="검색어")),
                ("suggestions", models.JSONField(verbose_name="추천 질문 목록")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
            ],
            options={
                "verbose_name": "추천 질문",
                "verbose_name_plural": "추천 질문 목록",
                "db_table": "recommended_questions_mv",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField(verbose_name="검색 질의")),
                (
                    "normalized_query",
                    models.TextField(
                        blank=True, null=True, verbose_name="정규화된 검색 질의"
                    ),
                ),
                (
                    "result_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="결과 개수"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="검색 시각"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "검색 로그",
                "verbose_name_plural": "검색 로그 목록",
                "db_table": "search_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="idx_searchlogs_created_at"
                    )
                ],
            },
        ),
    ]
