# Generated by Django 5.2.6 on 2025-09-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="검색어"
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="검색 횟수"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="갱신 시각"),
                ),
            ],
            options={
                "verbose_name": "인기 검색어",
                "verbose_name_plural": "인기 검색어 목록",
                "db_table": "popular_queries",
                "ordering": ["-count"],
            },
        ),
        migrations.CreateModel(
            name="RecommendedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField(verbose_name="검색어")),
                ("suggestions", models.JSONField(verbose_name="추천 질문 목록")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
            ],
            options={
                "verbose_name": "추천 질문",
                "verbose_name_plural": "추천 질문 목록",
                "db_table": "recommended_questions",
                "indexes": [
                    models.Index(
                        fields=["query", "-created_at"],
                        name="recommended_query_3756bd_idx",
                    )
                ],
            },
        ),
    ]
