# Generated by Django 5.2.6 on 2025-09-23 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0002_popularquery_recommendedquestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="popularquery",
            options={
                "managed": False,
                "ordering": ["-count"],
                "verbose_name": "인기 검색어",
                "verbose_name_plural": "인기 검색어 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="recommendedquestion",
            options={
                "managed": False,
                "verbose_name": "추천 질문",
                "verbose_name_plural": "추천 질문 목록",
            },
        ),
        migrations.AddField(
            model_name="searchlog",
            name="normalized_query",
            field=models.TextField(
                blank=True, null=True, verbose_name="정규화된 검색 질의"
            ),
        ),
        migrations.AddIndex(
            model_name="searchlog",
            index=models.Index(fields=["created_at"], name="idx_searchlogs_created_at"),
        ),
    ]
