# Generated by Django 5.2.6 on 2025-09-15 08:52

import django.contrib.auth.models
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="이메일"
                    ),
                ),
                ("username", models.CharField(max_length=100, verbose_name="사용자명")),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="닉네임"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="프로필 이미지 URL",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="전화번호"
                    ),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="이메일 인증 시각"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="탈퇴일시"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
                "db_table": "users",
                "indexes": [
                    models.Index(models.F("username"), name="idx_users_username"),
                    models.Index(models.F("email"), name="idx_users_email"),
                    models.Index(models.F("created_at"), name="idx_users_created_at"),
                    models.Index(
                        models.F("created_at"),
                        condition=models.Q(
                            ("is_active", True), ("email_verified_at__isnull", False)
                        ),
                        name="idx_users_verified_active",
                    ),
                    models.Index(
                        models.F("created_at"),
                        condition=models.Q(("email_verified_at__isnull", True)),
                        name="idx_users_unverified",
                    ),
                    models.Index(
                        models.F("phone_number"),
                        condition=models.Q(("phone_number__isnull", False)),
                        name="idx_users_phone_present",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        name="uq_users_email_ci",
                    )
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
