# Generated by Django 5.2.6 on 2025-09-17 10:04

import apps.users.models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="이메일"
                    ),
                ),
                ("username", models.CharField(max_length=100, verbose_name="사용자명")),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="닉네임"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="프로필 이미지",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="전화번호"
                    ),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="이메일 인증 시각"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="탈퇴일시"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시각"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
                "db_table": "users",
            },
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="OAuthAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "구글"),
                            ("github", "깃허브"),
                            ("kakao", "카카오"),
                            ("naver", "네이버"),
                        ],
                        max_length=30,
                        verbose_name="공급자",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=191, verbose_name="공급자 사용자 식별자(sub)"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="공급자 이메일",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False, verbose_name="공급자 이메일 인증 여부"
                    ),
                ),
                (
                    "access_token",
                    models.TextField(blank=True, null=True, verbose_name="액세스 토큰"),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True, null=True, verbose_name="리프레시 토큰"
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="토큰 만료 시각"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "소셜 계정",
                "verbose_name_plural": "소셜 계정 목록",
                "db_table": "oauth_accounts",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="idx_users_created_at"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                condition=models.Q(("deactivated_at__isnull", False)),
                fields=["deactivated_at"],
                name="idx_users_deactivated_nonnull",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email", django.db.models.functions.text.Lower("email"))
                ),
                name="users_email_is_lower",
            ),
        ),
        migrations.AddIndex(
            model_name="oauthaccount",
            index=models.Index(fields=["user"], name="idx_oauth_user"),
        ),
        migrations.AddIndex(
            model_name="oauthaccount",
            index=models.Index(fields=["created_at"], name="idx_oauth_created"),
        ),
        migrations.AddConstraint(
            model_name="oauthaccount",
            constraint=models.UniqueConstraint(
                fields=("provider", "subject"), name="uq_oauth_provider_subject"
            ),
        ),
        migrations.AddConstraint(
            model_name="oauthaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("provider__in", ["google", "github", "kakao", "naver"])
                ),
                name="chk_oauth_provider",
            ),
        ),
    ]
