# Generated by Django 5.2.6 on 2025-09-15 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InferenceRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=50, verbose_name="사용 모델")),
                ("latency_ms", models.IntegerField(verbose_name="지연 시간(ms)")),
                (
                    "prompt_tokens",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="프롬프트 토큰 수"
                    ),
                ),
                (
                    "completion_tokens",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="응답 토큰 수"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "성공"), ("error", "오류")],
                        default="success",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="오류 코드"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시각"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_runs",
                        to="conversations.conversation",
                        verbose_name="대화",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inference_runs",
                        to="conversations.message",
                        verbose_name="관련 메시지",
                    ),
                ),
            ],
            options={
                "verbose_name": "추론 실행",
                "verbose_name_plural": "추론 실행 목록",
                "db_table": "inference_runs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation"], name="inference_r_convers_3d800c_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="inference_r_created_1c97b3_idx"
                    ),
                    models.Index(
                        fields=["status"], name="inference_r_status_88e52b_idx"
                    ),
                ],
            },
        ),
    ]
