# Generated by Django 5.2.6 on 2025-09-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inference", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inferencerun",
            name="error_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="오류 코드"
            ),
        ),
    ]
