# Generated by Django 5.2.6 on 2025-09-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inference", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencerun",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inferencerun",
            name="error_code",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="오류 코드"
            ),
        ),
        migrations.AlterField(
            model_name="inferencerun",
            name="model",
            field=models.CharField(max_length=100, verbose_name="사용 모델"),
        ),
    ]
