# Generated by Django 5.2.6 on 2025-09-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inference", "0002_alter_inferencerun_error_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencerun",
            name="check_pass",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Self-Check 통과 여부"
            ),
        ),
        migrations.AddField(
            model_name="inferencerun",
            name="retry_used",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Self-Check 재시도 여부"
            ),
        ),
        migrations.AddField(
            model_name="inferencerun",
            name="violations",
            field=models.JSONField(
                blank=True, null=True, verbose_name="규칙 위반 목록"
            ),
        ),
    ]
