# Generated by Django 5.2.6 on 2025-09-15 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conversations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="소유자",
            ),
        ),
        migrations.AddField(
            model_name="conversationtag",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="conversations.conversation",
                verbose_name="대화",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="conversations.conversation",
                verbose_name="대화",
            ),
        ),
        migrations.AddField(
            model_name="conversationtag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="conversations.tag",
                verbose_name="태그",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="tags",
            field=models.ManyToManyField(
                related_name="conversations",
                through="conversations.ConversationTag",
                to="conversations.tag",
                verbose_name="태그",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="messages_convers_3ebb41_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversationtag",
            constraint=models.UniqueConstraint(
                fields=("conversation", "tag"), name="uq_conversation_tag"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["owner"], name="conversatio_owner_i_67ec5d_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["created_at"], name="conversatio_created_694913_idx"
            ),
        ),
    ]
