# Generated by Django 5.2.6 on 2025-09-16 03:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="tags",
        ),
        migrations.DeleteModel(
            name="ConversationTag",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
