# Generated by Django 5.2.6 on 2025-09-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("user", "사용자"), ("ai", "AI")],
                max_length=10,
                verbose_name="역할",
            ),
        ),
    ]
